### ISSUE TITLE
When a user is searching for a pin that is a part of a set

### ISSUE THREAD

**Issue by scytherswings** [PinsterTeam/HTMLPrototypes#6]
We should only get one search result

**Comment by markmoser** [comment]
Are you asking for a page view, that is not a list w/ modal?

**Comment by scytherswings** [comment]
Ahh this is from a conversation with Sirena, this is a low-priority feature we probably won't have time to implement right now. It's just more of a less-weird user interface idea.

**Comment by markmoser** [comment]
I believe this is completed with 815d2ed6?

re-open if not.

**Comment by scytherswings** [comment]
👍
